data:
  location: "Zurich, Switzerland"
  num_customers: 9999
  graph_file: "src/data/graph_data/zurich.graphml"
  matrix_file: "src/data/graph_data/D_mat.npy"
  locations_file: "src/data/graph_data/locations.npy"

manifold:
  n_components: 3
  n_neighbors: 50
  graph_file: "src/data/graph_data/zurich.graphml"
  matrix_file: "src/data/graph_data/D_mat.npy"
  locations_file: "src/data/graph_data/locations.npy"


