solver:
  run: train
  logdir: main_model/logs/decoder_100_long_2
  max_epoch: 400
  test_every_epoch: 1
  save_every_epoch: 5
  log_per_iter: 1
  type: adamw
  weight_decay: 0.01
  lr: 0.00025
  lr_type: poly
  lr_power: 0.9
  accumulation_steps: 1
  progress_bar: true
  rand_seed: 22
  empty_cache: true
  ckpt: main_model/logs/decoder_100_long_2/checkpoints/00200.solver.tar
  clip_grad: 0.0
  wandb:
    project_name: decoder_100
    run_name: base_long_2_2
data:
  mesh:
    mesh_path: main_model/disk/problems/set_100/mesh_data.h5
  train:
    mode: train
    batch_size: 512
    num_workers: 4
    episodes: -1
    shuffle: true
    env:
      data_path: main_model/disk/problems/set_100/cvrp_data_train_100.h5
      sub_path: true
    disable: false
  test:
    mode: test
    batch_size: 64
    num_workers: 4
    episodes: -1
    shuffle: true
    env:
      data_path:
        100: main_model/disk/problems/set_100/cvrp_data_test_100.h5
        200: main_model/disk/problems/set_100/cvrp_data_test_200.h5
        500: main_model/disk/problems/set_100/cvrp_data_test_500.h5
        1000: main_model/disk/problems/set_100/cvrp_data_test_1000.h5
      sub_path: false
    disable: false
model:
  embedding_dim: 128
  decoder_layer_num: 6
  head_num: 8
  hidden_dim: 512
  pretrained_encoder:
    in_channels: 6
    hidden_channels: 256
    out_channels: 32
    ckp_path: main_model/logs/encoder_32/checkpoints/08000.solver.tar
    mesh_path: main_model/disk/meshes/sphere.obj
